pipeline {
    agent any
    environment {
        WORKSPACE='/Users/nareshsalla/.jenkins/workspace'
    }
    stages {
        stage('Checkout code') {
        steps {
            sh 'cd ${WORKSPACE}'
            checkout scm
        }
    }
        stage('build') {
            steps {
                sh '/usr/local/bin/aws sts get-caller-identity'
                sh 'pwd ${WORKSPACE}'
                sh '/usr/local/bin/aws cloudformation create-stack --stack-name my-first-ec2-stack --template-body file://${WORKSPACE}/CFT/ec2.yaml'
            }
        }
    }
}