pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'aws cloudformation create-stack --stack-name my-first-ec2-stack --template-body file://${WORKSPACE}/CFT/ec2.yaml'
            }
        }
    }
}